-- =============================================================================
-- 01_schema_types_and_tables.sql
-- KIDS_CONTROLLER – ENUM-Typen, Tabellen, Indizes, Constraints
-- =============================================================================
-- Ausführung: psql -h 192.168.50.10 -U kids_controller_admin -d kids_controller
--             -f 01_schema_types_and_tables.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- ENUM-Typen
-- ---------------------------------------------------------------------------

CREATE TYPE window_status_enum AS ENUM (
    'ACTIVE',
    'COMPLETED'
);

CREATE TYPE mode_enum AS ENUM (
    'TRIPLET',
    'PAIR',
    'SINGLE',
    'SKIP'
);

CREATE TYPE perm_code_enum AS ENUM (
    '123',
    '132',
    '213',
    '231',
    '312',
    '321'
);

CREATE TYPE pair_key_enum AS ENUM (
    '12',
    '13',
    '23'
);

-- ---------------------------------------------------------------------------
-- Tabelle: fairness_windows
-- ---------------------------------------------------------------------------

CREATE TABLE fairness_windows (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    window_id            CHAR(8)             NOT NULL,
    window_start_date    DATE                NOT NULL,
    window_status        window_status_enum  NOT NULL,
    window_index         SMALLINT            NOT NULL,
    window_size          SMALLINT            NOT NULL,
    permutation_sequence JSONB               NOT NULL,
    last_full_order      perm_code_enum      NULL,
    last_full_draw_date  DATE                NULL,
    last_mode            mode_enum           NULL,
    seed_material_hash   CHAR(64)            NOT NULL,
    shuffle_algorithm    VARCHAR(64)         NOT NULL,
    algorithm_version    VARCHAR(32)         NOT NULL,
    created_at           TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  fairness_windows IS
    'Dreier-Fairnessfenster à 12 Züge (6 Permutationen × 2)';
COMMENT ON COLUMN fairness_windows.window_id IS
    'Kurz-ID (8 Zeichen, alphanumerisch), kein UUID';
COMMENT ON COLUMN fairness_windows.window_index IS
    'Aktueller Fortschritt innerhalb des Fensters (0-11 = ACTIVE, 12 = COMPLETED)';
COMMENT ON COLUMN fairness_windows.permutation_sequence IS
    'JSONB-Array der 12 Permutationscodes in zufälliger Reihenfolge';
COMMENT ON COLUMN fairness_windows.last_full_order IS
    'Letzte vollständige Dreier-Permutation als perm_code_enum';
COMMENT ON COLUMN fairness_windows.last_mode IS
    'Letzter TRIPLET-/Fensterzustand; kein globaler letzter Modus';

CREATE UNIQUE INDEX uq_fairness_windows_window_id
    ON fairness_windows (window_id);
CREATE UNIQUE INDEX uq_active_window
    ON fairness_windows (window_status)
    WHERE window_status = 'ACTIVE';
CREATE INDEX idx_fairness_windows_created_at
    ON fairness_windows (created_at);
CREATE INDEX idx_fairness_windows_start_date
    ON fairness_windows (window_start_date);
CREATE INDEX idx_fairness_windows_status
    ON fairness_windows (window_status);

-- ---------------------------------------------------------------------------
-- Tabelle: draws
-- ---------------------------------------------------------------------------

CREATE TABLE draws (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_ts                      TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
    draw_date                    DATE              NOT NULL,
    request_id                   UUID              NOT NULL,
    window_id                    CHAR(8)           NULL,
    mode                         mode_enum         NOT NULL,
    present_mask                 SMALLINT          NOT NULL,
    window_index                 SMALLINT          NULL,
    active_window_index_snapshot SMALLINT          NULL,
    perm_code                    perm_code_enum    NULL,
    derived_from_last_full_order BOOLEAN           NOT NULL DEFAULT FALSE,
    is_effective                 BOOLEAN           NOT NULL DEFAULT TRUE,
    superseded_by_draw_id        BIGINT            NULL,
    pair_key                     pair_key_enum     NULL,
    pair_cycle_index             SMALLINT          NULL,
    pos1                         SMALLINT          NULL,
    pos2                         SMALLINT          NULL,
    pos3                         SMALLINT          NULL,
    stop_morning                 SMALLINT          NULL,
    stop_midday                  SMALLINT          NULL,
    algorithm_version            VARCHAR(32)       NOT NULL,
    seed_material_hash           CHAR(64)          NOT NULL,
    replay_context_hash          CHAR(64)          NOT NULL,
    note                         VARCHAR(255)      NULL
);

COMMENT ON TABLE  draws IS
    'Jeder einzelne Auslosungs-Vorgang; request_id ist immer gesetzt (NOT NULL)';
COMMENT ON COLUMN draws.present_mask IS
    'Bitmaske: 1=Leon, 2=Emmi, 4=Elsa; SMALLINT, kein JSON';
COMMENT ON COLUMN draws.window_index IS
    'Nur bei TRIPLET gesetzt, sonst NULL';
COMMENT ON COLUMN draws.pair_cycle_index IS
    'Nur bei PAIR gesetzt (0 oder 1), sonst NULL';
COMMENT ON COLUMN draws.perm_code IS
    'Nur bei TRIPLET gesetzt, sonst NULL';
COMMENT ON COLUMN draws.pos3 IS
    'Nur bei TRIPLET gesetzt, sonst NULL';
COMMENT ON COLUMN draws.request_id IS
    'UUID des aufrufenden Systems; niemals NULL';
COMMENT ON COLUMN draws.replay_context_hash IS
    'SHA-256 des normalisierten Replay-Kontexts';

CREATE INDEX idx_draws_draw_date        ON draws (draw_date DESC);
CREATE INDEX idx_draws_draw_date_mode   ON draws (draw_date, mode);
CREATE INDEX idx_draws_draw_date_window ON draws (draw_date, window_id);
CREATE INDEX idx_draws_request_id       ON draws (request_id);
CREATE INDEX idx_draws_window_id        ON draws (window_id);
CREATE INDEX idx_draws_is_effective     ON draws (is_effective) WHERE is_effective = TRUE;
CREATE INDEX idx_draws_mode             ON draws (mode);
CREATE INDEX idx_draws_pair_key         ON draws (pair_key);
CREATE INDEX idx_draws_pos1             ON draws (pos1);
CREATE INDEX idx_draws_pos2             ON draws (pos2);
CREATE INDEX idx_draws_pos3             ON draws (pos3);
CREATE UNIQUE INDEX uq_draws_request_id ON draws (request_id);
CREATE UNIQUE INDEX uq_effective_draw_per_date
    ON draws (draw_date)
    WHERE is_effective = TRUE;

ALTER TABLE draws
    ADD CONSTRAINT fk_draws_superseded_by
        FOREIGN KEY (superseded_by_draw_id)
        REFERENCES draws (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL;

ALTER TABLE draws
    ADD CONSTRAINT fk_draws_window
        FOREIGN KEY (window_id)
        REFERENCES fairness_windows (window_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- Tabelle: system_config
-- ---------------------------------------------------------------------------

CREATE TABLE system_config (
    key_name    VARCHAR(64)  NOT NULL PRIMARY KEY,
    value       VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  system_config IS
    'Schlüssel-Wert-Konfiguration; aktuell nur Seed-/Referenzdaten, kein Runtime-Input';
COMMENT ON COLUMN system_config.key_name IS
    'Konfigurationsschlüssel (PK)';
COMMENT ON COLUMN system_config.value IS
    'Konfigurationswert als VARCHAR(255)';
COMMENT ON COLUMN system_config.updated_at IS
    'Letzte Änderung; muss beim Upsert explizit gesetzt werden';

-- ---------------------------------------------------------------------------
-- Berechtigungen
-- ---------------------------------------------------------------------------

GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA public TO kids_controller_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kids_controller_admin;
GRANT USAGE ON ALL SEQUENCES          IN SCHEMA public TO kids_controller_admin;
